export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const PUT_PRODUCT_BY_ID_SUCCESS = 'PUT_PRODUCT_BY_ID_SUCCESS';
export const GET_TRL_SUCCESS = 'GET_TRL_SUCCESS';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const ERROR = 'ERROR';
